//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public long Id { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string InvoiceNumber { get; set; }
        public string SoldTo { get; set; }
        public Nullable<System.DateTime> SoldOn { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> Quantity { get; set; }
        public string SoldBy { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
